---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
      - '.git*'
  push:
    branches:
      - 'master'
      - 'dev*'
    paths-ignore:
      - '*.md'
      - '.git*'

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    strategy:
      matrix:
        name:
          - AC
          - AD
          - ADX
          - Alligator
          - ATR
          - Awesome
          - Bands
          - BearsPower
          - BullsPower
          - BWMFI
          - CCI
          - DeMarker
          # - ElliottWave
          - Envelopes
          - Force
          - Fractals
          - Gator
          - HeikenAshi
          - Ichimoku
          - MA
          - MA2
          - MACD
          - MFI
          - Momentum
          - OBV
          - OsMA
          - RSI
          - RVI
          - SAR
          - StdDev
          - Stochastic
          - SVE_Bollinger_Bands
          - TMA_Band_SVE_True
          - TMA_True
          - WPR
          - ZigZag
          # - eSAWA
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: master
          repository: EA31337/EA31337-classes
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2361
          path: ./${{ matrix.name }}/Stg_${{ matrix.name }}.mq4
          verbose: true
      - name: Copy Math includes
        run: Copy-Item -Recurse ../MetaTrader/MQL5/Include/Math Include/
      - name: Compile for MQL5
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2515
          path: ./${{ matrix.name }}/Stg_${{ matrix.name }}.mq5
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
